workflows:
  ios-workflow-id:
    name: iOS Sample Workflow
    max_build_duration: 30
    instance_type: mac_mini_m2 # التأكد من استخدام جهاز الماك ليتعرف على بيئة iOS

    scripts:
      - name: Set up iOS Environment
        script: | 
          # هذا الأمر يتأكد من اختيار نسخة Xcode الصحيحة للبناء
          sudo xcode-select -s /Applications/Xcode.app
          
      - name: Build Vexo App
        script: |
          # بناء التطبيق بصيغة Release لنظام ios
          # إذا كنت تستخدم Flutter، استبدل السطر التالي بـ: flutter build ipa --release --no-codesign
          xcodebuild -project "Vexo.xcodeproj" \
                     -scheme "Vexo" \
                     -sdk iphoneos \
                     -configuration Release \
                     archive -archivePath $PWD/build/Vexo.xcarchive
          
          # تصدير ملف الـ IPA
          xcodebuild -exportArchive \
                     -archivePath $PWD/build/Vexo.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath $PWD/build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa # هذا هو الملف الذي ستحمله لتستخدمه مع 3utools

    publishing:
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Vexo-Final-App
          path: "**/*.ipa"
