workflows:
  ios-workflow-id:
    name: iOS Sample Workflow
    max_build_duration: 30
    instance_type: mac_mini_m2

    scripts:
      - name: Build Vexo App
        script: | 
          # أمر بناء التطبيق
          xcodebuild -project "Vexo.xcodeproj" -scheme "Vexo" -sdk iphoneos -configuration Release build
          
    artifacts:
      # هذا القسم هو المسؤول عن إظهار الملف لك في المتصفح بعد انتهاء البناء
      - build/ios/ipa/*.ipa
      - "**/*.ipa"

    publishing:
      # التعديل هنا: حذفنا الشرطة (-) ليكون "dict" صحيح
      email:
        recipients:
          - mojahedmohdsaad@gmail.com # سيتم إرسال رابط التحميل لإيميلك أيضاً
        notify:
          success: true
          failure: true
